"""
Altalanos jatek beallitasok
"""

import math


RES = WIDTH, HEIGHT = 1280, 720
FPS = 60

PLAYER_POS = 8, 4.5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.005
PLAYER_ROT_SPEED = 0.005

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
